# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LZFPSStatusDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LZFPSStatusDemo

# 自定义弹窗
  pod 'JKAlertX', '~> 2.0.17'

end
